#
# Makefile for the linux kernel.
#

# Object file lists.

obj-y			:= core.o  irq.o timer.o dma.o \
			   pincontrol.o lradc.o usb.o clock.o asm9260_uart.o asm9260_canserial.o
obj-m			:=
obj-n			:=
obj-			:=

