#ifndef __MAC_H__
#define __MAC_H__

#define HW_MACCLKDIV          	0x800401F8
#define HW_ETH_BASE_ADDR        0x80500000
#define HW_ETH_MACCR            HW_ETH_BASE_ADDR + 0x0000
#define HW_ETH_MACFFR           HW_ETH_BASE_ADDR + 0x0004
#define HW_ETH_MACHTHR          HW_ETH_BASE_ADDR + 0x0008
#define HW_ETH_MACHTLR          HW_ETH_BASE_ADDR + 0x000C
#define HW_ETH_MACMIIAR         HW_ETH_BASE_ADDR + 0x0010
#define HW_ETH_MACMIIDR         HW_ETH_BASE_ADDR + 0x0014
#define HW_ETH_MACFCR           HW_ETH_BASE_ADDR + 0x0018
#define HW_ETH_MACVLANTR        HW_ETH_BASE_ADDR + 0x001C
#define HW_ETH_MACVR            HW_ETH_BASE_ADDR + 0x0020    //read only
#define HW_ETH_MACRWUFFR        HW_ETH_BASE_ADDR + 0x0028
#define HW_ETH_MACPMTCSR        HW_ETH_BASE_ADDR + 0x002C
#define HW_ETH_MACDBGR          HW_ETH_BASE_ADDR + 0x0034
#define HW_ETH_MACISR           HW_ETH_BASE_ADDR + 0x0038
#define HW_ETH_MACIMR           HW_ETH_BASE_ADDR + 0x003C
#define HW_ETH_MACA0HR          HW_ETH_BASE_ADDR + 0x0040
#define HW_ETH_MACA0LR          HW_ETH_BASE_ADDR + 0x0044
#define HW_ETH_MACA1HR          HW_ETH_BASE_ADDR + 0x0048
#define HW_ETH_MACA1LR          HW_ETH_BASE_ADDR + 0x004C
#define HW_ETH_MACA2HR          HW_ETH_BASE_ADDR + 0x0050
#define HW_ETH_MACA2LR          HW_ETH_BASE_ADDR + 0x0054
#define HW_ETH_MACA3HR          HW_ETH_BASE_ADDR + 0x0058
#define HW_ETH_MACA3LR          HW_ETH_BASE_ADDR + 0x005C
#define HW_ETH_MACA4HR          HW_ETH_BASE_ADDR + 0x0060
#define HW_ETH_MACA4LR          HW_ETH_BASE_ADDR + 0x0064
#define HW_ETH_MMCCR            HW_ETH_BASE_ADDR + 0x0100
#define HW_ETH_MMCRIR           HW_ETH_BASE_ADDR + 0x0104
#define HW_ETH_MMCTIR           HW_ETH_BASE_ADDR + 0x0108
#define HW_ETH_MMCRIMR          HW_ETH_BASE_ADDR + 0x010C
#define HW_ETH_MMCTIMR          HW_ETH_BASE_ADDR + 0x0110
#define HW_ETH_MMCTGFSCCR       HW_ETH_BASE_ADDR + 0x014C
#define HW_ETH_MMCTGFMSCCR      HW_ETH_BASE_ADDR + 0x0150
#define HW_ETH_MMCTGFCR         HW_ETH_BASE_ADDR + 0x0168
#define HW_ETH_MMCRFCECR        HW_ETH_BASE_ADDR + 0x0194
#define HW_ETH_MMCRFAECR        HW_ETH_BASE_ADDR + 0x0198
#define HW_ETH_MMCRGUFCR        HW_ETH_BASE_ADDR + 0x01C4
#define HW_ETH_PTPTSCR          HW_ETH_BASE_ADDR + 0x0700
#define HW_ETH_PTPSSIR          HW_ETH_BASE_ADDR + 0x0704
#define HW_ETH_PTPTSHR          HW_ETH_BASE_ADDR + 0x0708
#define HW_ETH_PTPTSLR          HW_ETH_BASE_ADDR + 0x070C
#define HW_ETH_PTPTSHUR         HW_ETH_BASE_ADDR + 0x0710
#define HW_ETH_PTPTSLUR         HW_ETH_BASE_ADDR + 0x0714
#define HW_ETH_PTPTSAR          HW_ETH_BASE_ADDR + 0x0718
#define HW_ETH_PTPTTHR          HW_ETH_BASE_ADDR + 0x071C
#define HW_ETH_PTPTTLR          HW_ETH_BASE_ADDR + 0x0720
#define HW_ETH_DMABMR           HW_ETH_BASE_ADDR + 0x1000
#define HW_ETH_DMATPDR          HW_ETH_BASE_ADDR + 0x1004
#define HW_ETH_DMARPDR          HW_ETH_BASE_ADDR + 0x1008
#define HW_ETH_DMARDLAR         HW_ETH_BASE_ADDR + 0x100C
#define HW_ETH_DMATDLAR         HW_ETH_BASE_ADDR + 0x1010
#define HW_ETH_DMASR            HW_ETH_BASE_ADDR + 0x1014
#define HW_ETH_DMAOMR           HW_ETH_BASE_ADDR + 0x1018
#define HW_ETH_DMAIER           HW_ETH_BASE_ADDR + 0x101C
#define HW_ETH_DMAMFBOCR        HW_ETH_BASE_ADDR + 0x1020
#define HW_ETH_DMACHTDR         HW_ETH_BASE_ADDR + 0x1048
#define HW_ETH_DMACHRDR         HW_ETH_BASE_ADDR + 0x104C
#define HW_ETH_DMACHTBAR        HW_ETH_BASE_ADDR + 0x1050
#define HW_ETH_DMACHRBAR        HW_ETH_BASE_ADDR + 0x1054

#endif   /* __MAC_H__ */
