# ASM9260 Platform Support
snd-soc-asm9260-objs := asm9260-pcm.o
snd-soc-asm9260-i2s-objs := asm9260-i2s.o

obj-$(CONFIG_SND_ASM9260_SOC) += snd-soc-asm9260.o
obj-$(CONFIG_SND_ASM9260_SOC_I2S) += snd-soc-asm9260-i2s.o

# ASM9260 Machine Support
snd-soc-asm9260-wm8731-objs := asm9260_wm8731.o

obj-$(CONFIG_SND_ASM9260_SOC_IIS_WM8731) += snd-soc-asm9260-wm8731.o

