# PXA Platform Support
snd-soc-pxa2xx-objs := pxa2xx-pcm.o
snd-soc-as3310x-ac97-objs := as3310x-ac97.o
snd-soc-as3310x-i2s-objs := as3310x-i2s.o

obj-$(CONFIG_SND_as3310x_SOC) += snd-soc-as3310x.o
obj-$(CONFIG_SND_as3310x_SOC_AC97) += snd-soc-as3310x-ac97.o
obj-$(CONFIG_SND_as3310x_SOC_I2S) += snd-soc-as3310x-i2s.o


